version: '3'

services:

  nginx:
    image: nginx:1.15-alpine
    container_name: demo-nginx
    restart: always
    links:
      - php:php
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www

  php:
    user: '1000'
    restart: always
    container_name: demo-fpm
    build:
      context: ./.docker/fpm
    volumes:
      - ./.docker/fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/fpm/php.dev.ini:/usr/local/etc/php/conf.d/php.dev.ini
      - ./:/var/www
